### ISSUE TITLE
Add requirements.txt and README file explaining how to execute the code

### ISSUE THREAD

**Issue by dorchard** [Spacesmac/SonicPi_Looper#20]

**Comment by dorchard** [comment]
Looks like the requirements are just:
```
PyQt5
python-osc
```

**Comment by Spacesmac** [comment]
Thank you so much, that's valuable information for me !
________________________________
De : Dominic Orchard ***@***.***>
Envoyé : vendredi 9 août 2024 13:26
À : Spacesmac/SonicPi_Looper ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [Spacesmac/SonicPi_Looper] Add requirements.txt and README file explaining how to execute the code (Issue #20)


Looks like the requirements are just:

PyQt5
python-osc

**Comment by Spacesmac** [comment]
All done, you can take a look at the ReadMe if you want. I will now submit the Corpus, unless you have any last tasks !
